### ISSUE TITLE
Consolidate `softUpdate` and `hardUpdate`?

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/freactal#10]
Right now, `freactal` provides a `hardUpdate` helper:
```
import { provideState, hardUpdate } from "freactal";
const wrapComponentWithState = provideState({
  // ...
  effects: {
    myEffect: hardUpdate({ setThisKey: "to this value..." })
  }
});
```

...and a `softUpdate` helper:
```
import { provideState, softUpdate } from "freactal";
const wrapComponentWithState = provideState({
  // ...
  effects: {
    myEffect: softUpdate(state => ({ counter: state.counter + 1 }))
  }
});
```
... where the core difference is that `hardUpdate` takes a partial state object (independent of previous state), while `softUpdate` takes a function that's called with `state` and returns a partial state object.

What if we combined both into a single `update` helper that 1.) behaves like `hardUpdate` if you call it with an object and 2.) behaves like `softUpdate` if you call it with a function? The idea is that both of these would be possible:
```
effects: {
  resetCounter: update({ counter: 0 }),
  incrementCounter: update(state => ({ counter: state.counter + 1 }))
}
```

**Comment by drcmda** [comment]
Very much in favour of this. I find semantic notions like hardUpdate and softUpdate very arbitrary and hard to remember. `update` tells what it does by how it's being used, also it feels right at home (`setState`).

**Comment by divmain** [comment]
This'll be going in as soon as the PR is ready.
