### ISSUE TITLE
Question about the necessity of lodash

### ISSUE THREAD

**Issue by bali182** [FormidableLabs/freactal#24]
Quick search for the keyword `lodash` shows that 3 functions are used, and they are painlessly replaceable:

- `keys` - `Object.keys`
- `assign` - `Object.assign`
- `isFunction` -  `instanceof Function` or just steal the snippet https://github.com/lodash/lodash/blob/3.0.8-npm-packages/lodash.isfunction/index.js

Would this something you are interested in?

**Comment by divmain** [comment]
Lodash methods tend to be faster than their native counterparts (for now), and since this is only pulled in on the server, it won't result in a larger bundle size.  Is there a particular reason you'd remove it, or is mostly about removing a dependency?

**Comment by bali182** [comment]
@divmain  You are absolutely right! I just get triggered too quickly when I see lodash with destructuring imports in a small lib 😄 

Didn't even know this lib has a server part, I was thinking it's purely for frontend state management.

**Comment by divmain** [comment]
No worries!  And thanks for keeping me honest :)
