### ISSUE TITLE
Question: Initialize state to props?

### ISSUE THREAD

**Issue by alexknipfer** [FormidableLabs/freactal#39]
What's the best way to initialize state to a specific prop value?
Or, how do I access props within initialState?
Obviously, using React's state you would just set the initial state to `this.props.value`, but what is the correct way to do so with freactal?

For example:

```
const wrapComponentWithState = provideState({
  initialState: () => ({
    testValue:   //Initialize to prop value here
  })
})
```

**Comment by aweary** [comment]
Freactal passes [`props` and `context` to `initialState`](https://github.com/FormidableLabs/freactal/blob/95cf1bd6b8aa67a4535fcb81c9946bf2b623cec6/src/provide.js#L126), so it would just look like:

```js
const wrapComponentWithState = provideState({
  initialState: (props) => ({
    testValue:   props.value
  })
})
```

**Comment by alexknipfer** [comment]
Oh, perfect! Thanks so much!
