### ISSUE TITLE
How to access state after effects complete in middleware?

### ISSUE THREAD

**Issue by JoeZheng2015** [FormidableLabs/freactal#62]
In freactal v1.1.0, I want to track the state changes in middleware for debugging just like what [redux-logger](https://github.com/evgenyrodionov/redux-logger) did. However I find that I can't access the latest state after effects complete in middleware.

Am I missing anything? And it would be fabulous if you could help me out. Thanks!

**Comment by divmain** [comment]
Hi @JoeZheng2015!  Thanks for opening the PR!  I've merged in the changes (which was my intended behavior, anyway :) ), and they'll be included in the next release!

**Comment by JoeZheng2015** [comment]
@divmain Thanks :)
