### ISSUE TITLE
Example won't work

### ISSUE THREAD

**Issue by tomexa** [FormidableLabs/freactal#75]
Hi, 
I cloned this repository, installed dependencies in the main folder and in the example folder, and ran the build script successfully for freactal.
But when I start and go to localhost:1337, almost every variable is undefined. 
I see the network call when I click on the fetch button and it returns a list of todos, but nothing changes on screen.
It's like the state is never changed.
I also tried to extract the example by putting src and package.json in a new folder and added freactal as a dependency and running it from there but it didn't change anything.
(By the way, I had to import the function `initialize`from `freactal/lib/server` and not `freactal/server`) 

Did I miss something? 

![capture d ecran 2017-08-09 a 12 28 57](https://user-images.githubusercontent.com/23457258/29117430-6dabcd6e-7cfe-11e7-86d1-f794f80e007a.png)

**Comment by BasileTrujillo** [comment]
Hi,

It seams to work on 1.1.0 but not on 1.1.1.

**Comment by Jascha-Sundaresan** [comment]
Has anybody figured out what broke between 1.1.0 and 1.1.1 wrt SSR?

**Comment by Jascha-Sundaresan** [comment]
fixed this in https://github.com/FormidableLabs/freactal/pull/76

**Comment by divmain** [comment]
This should be fixed.  Thanks @Jascha-Sundaresan!
