### ISSUE TITLE
Component life cycle

### ISSUE THREAD

**Issue by HamadaBrest** [FormidableLabs/freactal#77]
Does components that you have used in documentation extend from React Component ? 
Because I can't set the componentWillMount() !

**Comment by Jascha-Sundaresan** [comment]
components written as functional stateless components don't have lifecycle hooks.

You'll need to do the `class YourComponent extends React.Component...` pattern for creating components that you want to have lifecycle hooks for.

Alternatively, you can use Recompose's lifecycle hoc.

**Comment by Jascha-Sundaresan** [comment]
Why do you need to use componentWillMount anyways? What do you need to accomplish that can't be done w/ the initialize effect?

**Comment by HamadaBrest** [comment]
@Jascha-Sundaresan Thank you I solved the problem with initialize effect, it's just that documentation is not clear enough, but I'm impressed with your way for managing states in react app :+1:  
Continue to improve this library :+1:

**Comment by Jascha-Sundaresan** [comment]
can this be closed @HamadaBrest?

**Comment by HamadaBrest** [comment]
@Jascha-Sundaresan  Yes of course :) thank you
