### ISSUE TITLE
Recompose nice usage

### ISSUE THREAD

**Issue by giltig** [FormidableLabs/freactal#83]
Hi,
Very interesting library.
However, 
We actually implemented these features and more with recompose which is more generic pretty easily.

What this library enables which recompose doesn't?

**Comment by divmain** [comment]
That... is a very difficult question to answer.  I think the most obvious thing would be effect composition, but `recompose` and `freactal` are solving different problems, and are actually quite complimentary.  I'm going to leave it at that.  If you have a more specific question I can answer, feel free to ask!.
