### ISSUE TITLE
Any intention to support decorators?

### ISSUE THREAD

**Issue by huttj** [FormidableLabs/freactal#87]
I'm a fan of MobX, particularly the way that it leverages [decorators](https://mobx.js.org/refguide/observable-decorator.html). Freactal seems very interesting, and I would definitely prefer to use decorators if possible.

**Comment by gustavohenke** [comment]
I think you can just use it. Decorators are just regular functions.

**Comment by huttj** [comment]
Oh? I've played with them with Babel, and I was under the impression that the meta stuff was requires, as outlined [here](https://github.com/tc39/proposal-decorators/blob/master/METAPROGRAMMING.md).

I'll see if I can just use the functions directly and report back.

**Comment by gustavohenke** [comment]
That applies to decorators that change an object's properties.
If you are decorating a React component, there's nothing to do except wrap it with other components!

**Comment by huttj** [comment]
I tried to recreate the example with the functions as decorators, and it didn't work. The Babel plugin requires the decorators to be applied to a class or to a method, not to a freestanding function. Is there another plugin that would let me apply them to stateless functional components?

**Comment by julien-f** [comment]
Function decorators have not yet been specified by a [TC39 proposal](https://github.com/tc39/proposals) due to issues with hoisting, for the time being we have to call them as functions…

**Comment by huttj** [comment]
So, looks like the answer is no, contingent on function decorators being spec'd. Thanks.
